spring.application.name=order-service
spring.config.import=configserver:http://localhost:8888

# ==========================================
# Kafka Producer Configuration
# ==========================================

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Serialize the message key as String
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Serialize the message value as JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer