server.port=8888

spring.application.name=CONFIG-SERVER

spring.cloud.config.server.git.uri=file:///D:/self-learning/00/05-microservices/005-spring-cloud-config-server/config-repo
#spring.cloud.config.server.git.uri=https://github.com/your-user/config-repo

spring.cloud.config.server.git.clone-on-start=true